### ISSUE TITLE
2 map functions samenvoegen? Of niet (reusability)?

### ISSUE THREAD

**Issue by ralfz123** [ralfz123/functional-programming#1]
https://github.com/ralfz123/functional-programming/blob/main/script.js#L20-L33

**Comment by RowinRuizendaal** [comment]
I am not sure what you mean to merge the 2 map functions together, Also I don't know what is happening on some lines because I don't know the exact data that is being processed right there. Also, I wouldn't recommend clustering the map functions together (if that is what you want to do) because it will be harder to read for someone to understand what you are mapping exactly.

that being said: I've had a look at your code and made a quick refactor code for you I made this example pretty fast so maybe you can even make it prettier :D

```js
const name = ['', '', 'Aardappel', '', 'Naam1', '', '', 'Tommy', '',
  'Sapjes', '', '/', '', 'Kaas', '    ', '', 'geen', '', 'nvt', '',
  '-', '', 'geen', ''];


const z = name.map((name) => {
  const tempName = name.trim().toLowerCase();

  if (tempName == 'geen' || tempName == 'nvt' || tempName == '-' || tempName == '/' || tempName == '') {
    return null;
  }
  return name;
});

console.log(z);
```

I can agree that the if statement is kinda messy, but since you need to hardcode this I think that is your only way to go :), Also with this example, you don't need an index of (Credits to Sam for testing this in the node environment ) :)
